### ISSUE TITLE
[Server Crash] 

### ISSUE THREAD

**Issue by NikeSchuh** [Vllaxa/arthropod#1]
[crash-2024-04-04_16.31.29-server.txt](https://github.com/Vllaxa/arthropod/files/14872791/crash-2024-04-04_16.31.29-server.txt)

**Comment by Vllaxa** [comment]
Thanks for the info - I'm currently finalising the next mod version (1.8, will be released today), and will add a safeguard that should hopefully prevent this type of crash.
