### ISSUE TITLE
crash with reliquary

### ISSUE THREAD

**Issue by pibblepower** [Vllaxa/arthropod#4]
when interacting (fighting) with one of the mobs (a house-centipede thing, I forgot the name), the server crashed. It seems to be related to reliquary's charm items (which are possible mob drops). I'm playing on 1.20.1. Here's the crash report: 
[crash-2024-09-24_14.18.36-server.txt](https://github.com/user-attachments/files/17120136/crash-2024-09-24_14.18.36-server.txt)

**Comment by Vllaxa** [comment]
Crash seems to be caused by reliquary, in the way that the reliquary item tried to check something with the ArPhEx mob, as far as I can tell :)
