### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by pibblepower** [Vllaxa/arthropod#5]
I'm playing the game, and it crashes out of nowhere at random intervals at my base. looking through the crash report, it seems to crash due to a mob called a Centipede Evictor Larvae on the walls of my base. here's a crash report: 
[crash-2024-09-24_22.29.47-client.txt](https://github.com/user-attachments/files/17123656/crash-2024-09-24_22.29.47-client.txt)

**Comment by Vllaxa** [comment]
Added some safeguards to prevent this - seems to be a crash linked to Reliquary compatibility.
