### ISSUE TITLE
Spider Jar failing to capture tamed spider

### ISSUE THREAD

**Issue by Acenthus** [Vllaxa/arthropod#6]
I have a tamed Jumping Spider (btw related, why are the jumping spiders just called "Spider Jump"?) that when attempting to right click with the spider jar nothing occurs. I have a very extensive modpack that I'm using so hopefully there's a way to tell what is specifically causing this. I attached the Curseforge zip that can be used to import the modpack since it's not published to Curseforge yet.
[Strikecraft.zip](https://github.com/user-attachments/files/17177123/Strikecraft.zip)

**Comment by Vllaxa** [comment]
Hi, thanks for letting me know - I've just tried it with the modpack and I was able to pick up tamed spider jumps every time. If you send the world file, that could make it possible to diagnose. The name is just based on the simple formulaic arphex naming scheme for all non-boss mobs  :)

**Comment by Acenthus** [comment]
Oh sorry I only just noticed that you actually responded immediately, used to Devs taking ages lol. I'll try to give you the world file tomorrow, and also the config file since I just realized that has a chance of effecting it too. Oh alright cool lol.

**Comment by Vllaxa** [comment]
Great 👍
